- name: Install banana apt dependencies.
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: "{{ lookup('file', 'banana-apt-deps.txt').split() }}"
  sudo: yes
  tags: apt

- name: Install banana build-dependencies.
  apt: name={{item}} state=build-dep
  with_items:
    - python-numpy
    - python-matplotlib
  sudo: yes
  tags: apt



- name: Create repo / venv dir with correct permissions
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
    owner: "{{ banana_deploy_user }}"
    group: "{{ banana_apache_user }}"
#    recurse: true
  with_items:
    - "{{ banana_repo_path }}"
    - "{{ banana_venv }}"
  sudo: yes


- name: Clone banana repo
  git:
    repo: https://github.com/transientskp/banana.git
    dest: "{{ banana_repo_path }}"
    force: yes
    version: "{{ banana_version }}"
  become: yes
  become_user: "{{ banana_deploy_user }}"
  register: banana_repo_clone_result
  
  
- name: Install requirements into v-env
  pip:
    requirements: "requirements.txt"
    chdir: "{{ banana_repo_path }}"
    virtualenv: "{{ banana_venv }}"
  become: yes
  become_user: "{{ banana_deploy_user }}"
  
#- name: Install banana into v-env
#  pip:
#    name: ".[all]"
##    extra_args: "-e"
#    state: latest
#    chdir: "{{ banana_repo_path }}"
#    virtualenv: "{{ banana_venv }}"
#  when: banana_repo_clone_result | changed
#  become: yes
#  become_user: "{{ banana_deploy_user }}"

- name: Notify restart-apache if banana updated
  debug: msg="banana updated, will notify apache-restart"
  when: banana_repo_clone_result | changed
  changed_when: True
  notify:
    - restart apache

- name: Upload templated banana local-settings
  template:
    src: banana_local.py.j2
    dest: "{{ banana_repo_path }}/project/settings/local.py"
    owner: "{{ banana_deploy_user }}"
    group: "{{ banana_apache_user }}"
    mode: "u=rw,g=r,o=r"
  sudo: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache

- name: Upload templated banana wsgi config
  template:
    src: banana.wsgi.j2
    dest: "{{ banana_repo_path }}/project/wsgi.py"
    owner: "{{ banana_deploy_user }}"
    group: "{{ banana_apache_user }}"
    mode: "u=rw,g=r,o=r"
  sudo: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache

- name: Collect static files
  shell:
      . {{ banana_venv }}/bin/activate &&
      ./manage.py collectstatic --noinput
  args:
    chdir: "{{ banana_repo_path }}"
  changed_when: False