- name: Enable mod_wsgi, mod_rewrite
  apache2_module: state=present name={{item}}
  with_items:
    - wsgi
    - rewrite
  become: yes
  notify: restart apache

- name: Enable mod_version if running 12.04/precise/Apache2.2
  apache2_module: state=present name=version
  when: banana_apache_version == "2.2"
  become: yes
  notify: restart apache

- set_fact:
    banana_siteconf_file_suffix: ".conf"
  when: banana_apache_version == "2.4"

- name: Disable default siteconf
  command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache

# Now for a bit of apache virtualhost chicanery
# This allows us to run multiple versions of banana in parallel, using
# different url-subdirectories for each version:

- name: Create 'banana-subsites' apache confdir
  file:
    path: "/etc/apache2/{{ banana_apache_subsite_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: yes


- name: Upload top-level banana virtualhost definition conf
  template:
    src: banana_vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ banana_apache_sitename }}{{ banana_siteconf_file_suffix }}"
    owner: root
    mode: "u=rw,g=r,o=r"
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache


- name: Upload version-specific subsite / subdirectory configuration
  template:
    src: banana_subsite.conf.j2
    dest: "/etc/apache2/{{ banana_apache_subsite_dir }}/{{ banana_version_shortname }}.conf"
    owner: root
    mode: "u=rw,g=r,o=r"
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache

- name: Enable banana siteconf
  command: a2ensite {{ banana_apache_sitename }}
  args:
    creates: "/etc/apache2/sites-enabled/{{ banana_apache_sitename }}{{ banana_siteconf_file_suffix }}"
  become: yes
  #Restart service if init-script has changed:
  notify:
    - restart apache